scan-logic:
  stage: pre-scan
  extends:
    - .setup_modules
  needs:
    - setup
    - build
    - create-sbom
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      dotenv: scan_logic.env
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/4-pre-scan/scan_logic_jobs.py"'
  retry:
    max: 2
    when: runner_system_failure

scan-logic-arm64:
  stage: pre-scan
  extends:
    - .setup_modules
  needs:
    - setup
    - build-arm64
    - create-sbom-arm64
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      dotenv: scan_logic.env
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/4-pre-scan/scan_logic_jobs.py"'
  retry:
    max: 2
    when: runner_system_failure
  rules:
    - exists:
        - Dockerfile_arm64
