[tool.poetry]
name = "ibmodules"
version = "0.1.0"
description = ""
authors = ["Kenneth Maguire <kenneth.maguire.ctr@us.af.mil>"]

packages = [
    { include = "ibmodules" }
]

[tool.poetry.dependencies]
python = "^3.10"
boto3 = "^1.24.4"
dockerfile = "^3.2.0"
gitpython = "^3.1.27"
jsonschema = "^4.6.0"
openpyxl = "^3.0.10"
pandas = "^1.4.2"
pytest = "^7.1.2"
python-gitlab = "^3.5.0"
pyyaml = "^6.0"
requests = "^2.27.1"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
