# skip_strings:
#   "stages/preflight/README.md":
#     - airflow_conf_set
# skip_paths: []
exclude:
  - message: Standard pipeline config
    pattern: airflow_conf_set
    paths:
      - stages/preflight/README.md