.preflight:
  stage: preflight
  # Load in the IMAGE_VERSION variable from the load-scripts env
  dependencies:
    - load-scripts

include:
  - local: stages/preflight/trufflehog.yaml
  - local: stages/preflight/folder-structure.yaml
  - local: stages/preflight/hardening-manifest.yaml
  - local: stages/preflight/registry-validation.yaml
# TODO: Possibly check for deployment files?
