.preflight:
  stage: preflight
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/docker-git-bash-python:3.7
  

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - ls -l README.md
    - ls -l Dockerfile
    - ls -l LICENSE
    # - ls -l download.yaml || echo "No download.yaml found"
    # - ls -l scripts || echo "No download.yaml found"
    # - ls -l signatures || echo "No download.yaml found"
    # - ls -l config || echo "No download.yaml found"
    # - ls -l accreditation || echo "No download.yaml found"

# TODO: Check the following (among others):
# base image vars??
# OPTIONAL FOR BETA PIPELINE
build variables:
  extends: folder structure
  script:
    - |
      if [ -z "$IMG_VERSION" ]; then
        echo "Missing IMG_VERSION variable in .gitlab-ci.yml file"
        exit 1
      fi
