.preflight:
  stage: preflight

  dependencies:
    - load scripts

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - |
      if ! [[ -f README.md ]]; then
        echo "README.md not found"
      fi
      if ! [[ -f Dockerfile ]]; then
        echo "Dockerfile not found"
      fi
      if ! [[ -f "LICENSE" || -f "LICENSE.md" || -f "LICENSE.txt" || -f "LICENSE.adoc" ]]; then
        echo "LICENSE not found"
      fi

# build variables:
#   extends: folder structure
#   script:
#     - '"${PIPELINE_REPO_DIR}/stages/preflight/check_base_vars.sh"'

source variables:
  extends: .preflight
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/preflight"
  script:
    - mkdir -p "${ARTIFACT_STORAGE}/preflight"
    - pip3 install jsonschema
    - python3 "${PIPELINE_REPO_DIR}/stages/preflight/source_variables.py"
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: "${ARTIFACT_DIR}/name.env"
