.preflight:
  stage: preflight
  image: ${REGISTRY_URL}/gitlab/gitlab-runner/gitlab-runner:v13.2.2
  allow_failure: true
  

# TODO: Possibly check for deployment files?
folder_structure:
  extends: .preflight
  allow_failure: true
  script:
    - ls -l README.md
    - ls -l Dockerfile
    - ls -l LICENSE
    - ls -l download.yaml || echo "No download.yaml found"
    - ls -l scripts || echo "No download.yaml found"
    - ls -l signatures || echo "No download.yaml found"
    - ls -l config || echo "No download.yaml found"
    - ls -l accreditation || echo "No download.yaml found"

# TODO: Check the following (among others):
# base image vars??
# OPTIONAL FOR BETA PIPELINE
build variables:
  extends: folder_structure
  allow_failure: true
  script:
    - |
      if [ -z "$IMG_VERSION" ]; then
        echo "Missing IMG_VERSION variable"
        exit 1
      fi

  
