.preflight:
  stage: preflight
  tags:
    - ironbank
  # Load in the IMG_VERSION variable from the load scripts env
  dependencies:
    - load scripts

include:
  - local: stages/preflight/trufflehog.yaml
  - local: stages/preflight/folder-structure.yaml
  - local: stages/preflight/hardening-manifest.yaml
# TODO: Possibly check for deployment files?
