.preflight:
  stage: preflight

  # Load in the IMG_VERSION variable from the load scripts env
  dependencies:
    - load scripts

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - |
      # Check if required files exist
      # Testing with `-f` avoids the scenario where a malicious symlink is is named `README` in the repository
      if ! [[ -f README.md ]]; then
        echo "README.md not found"
      fi
      if ! [[ -f Dockerfile ]]; then
        echo "Docker file not found"
      fi
      if ! [[ -f "LICENSE" ]]; then
        echo "LICENSE not found"
      fi

    # - ls -l download.yaml || echo "No download.yaml found"
    # - ls -l scripts || echo "No download.yaml found"
    # - ls -l signatures || echo "No download.yaml found"
    # - ls -l config || echo "No download.yaml found"
    # - ls -l accreditation || echo "No download.yaml found"

# TODO: Check the following (among others):
# base image vars??
# OPTIONAL FOR BETA PIPELINE
build variables:
  extends: folder structure
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/check_base_vars.sh"'
