.preflight:
  stage: preflight
  allow_failure: true

# TODO: implement check for Dockerfile, LICENSE, and README
# Possibly check for deployment files?
.folder_structure:
  extends: .preflight
  allow_failure: true
  script:
    - ls -l README.md
    - ls -l Dockerfile
    - ls -l LICENSE
    - ls -l download.yaml
    - ls -l scripts
    - ls -l signatures
    - ls -l config
    - ls -l accreditation

# TODO: Check the following (among others):
# base image vars??
# OPTIONAL FOR BETA PIPELINE
build variables:
  extends: .folder_structure
  allow_failure: true
  script:
    - |
      if [ -z "$IMG_VERSION" ]; then
        echo "Missing IMG_VERSION variable"
        exit 1
      fi

  
