.preflight:
  stage: preflight

  # Load in the IMG_VERSION variable from the load scripts env
  dependencies:
    - load scripts

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - |
      if ! [[ -f README.md ]]; then
        echo "README.md not found"
      fi
      if ! [[ -f Dockerfile ]]; then
        echo "Dockerfile not found"
      fi
      if ! [[ -f "LICENSE" || -f "LICENSE.md" || -f "LICENSE.txt" || -f "LICENSE.adoc" ]]; then
        echo "LICENSE not found"
      fi

build variables:
  extends: folder structure
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/check_base_vars.sh"'

source variables:
  extends: build variables
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/source_variables.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: source.env
