.preflight:
  stage: preflight
  image: "${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/docker-git-bash-python:3.7"

  # Load in the IMG_VERSION variable from the load scripts env
  dependencies:
    - load scripts

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - |
        OUTPUT1=$([[ -f README.md ]])
        echo "${OUTPUT1}"
        OUTPUT2=$([[ -f Dockerfile ]])
        echo "${OUTPUT2}"
        OUTPUT3=$([[ -f "LICENSE" || -f "LICENSE.md" || -f "LICENSE.txt" || -f "LICENSE.txt" ]])
        echo "${OUTPUT3}"
    # - ls -l download.yaml || echo "No download.yaml found"
    # - ls -l scripts || echo "No download.yaml found"
    # - ls -l signatures || echo "No download.yaml found"
    # - ls -l config || echo "No download.yaml found"
    # - ls -l accreditation || echo "No download.yaml found"

# TODO: Check the following (among others):
# base image vars??
# OPTIONAL FOR BETA PIPELINE
build variables:
  extends: folder structure
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/check_base_vars.sh"'
