.preflight:
  stage: preflight
  tags:
    - ironbank
  # Load in the IMG_VERSION variable from the load scripts env
  dependencies:
    - load scripts

# TODO: Possibly check for deployment files?
folder structure:
  extends: .preflight
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/folder_structure.sh"'

# TODO: Check the following (among others):
# base image vars??
build variables:
  extends: folder structure
  script:
    - '"${PIPELINE_REPO_DIR}/stages/preflight/check_base_vars.sh"'
