csv-output:
  stage: csv-output
  dependencies:
    - twistlock-scan
    - openscap-compliance
    - vat
    - anchore-scan
    - load-scripts
    - hardening-manifest
    - base-image-validation
    - wl-compare-lint
    - build
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/csv-output/csv-output.sh"'
  artifacts:
    when: always
    paths:
      - "${CSV_REPORT}"
    reports:
      dotenv: csv_output.env
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
