.csv-output:
  stage: csv output
  image: "${REGISTRY_URL}/redhat/python/python36:3.6"
  dependencies:
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
    - load scripts
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs/"