csv output:
  stage: csv output
  tags:
    - ironbank
  dependencies:
    - twistlock scan
    - openscap compliance
    - anchore scan
    - load scripts
    - hardening_manifest
    - wl compare lint
    - build
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs"
  script:
    - pip3 install jsonschema
    - '"${PIPELINE_REPO_DIR}/stages/csv-output/csv-output.sh"'
  artifacts:
    when: always
    paths:
      - "${CSV_REPORT}"
    reports:
      dotenv: csv_output.env
    expire_in: 1 week
