csv-output:
  stage: csv-output
  allow_failure: true
  image: ${REGISTRY_URL}/redhat/python/python36:3.6
  dependencies:
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: ${ARTIFACT_STORAGE}/scan-results/csv-output
  before_script:
    - mkdir -p "${CSV_REPORT}"
  script:
    - python3 ${PIPELINE_REPO_DIR}/stages/csv-output/pipeline_csv_gen.py
  artifacts:
    when: always
    paths:
      - ${CSV_REPORT}/