csv output:
  stage: csv output
  image: "${BASE_REGISTRY}/redhat/python/python36:3.6"
  dependencies:
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
    - load scripts
    - wl compare lint
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs"
    DISTROLESS: "${DISTROLESS}"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/csv-output/csv-output.sh"'
  artifacts:
    when: always
    paths:
      - "${CSV_REPORT}"
    expire_in: 1 week

