csv-output:
  stage: csv-output
  needs:
    - load-scripts
    - lint
    - build
    - anchore-scan
    - openscap-compliance
    - twistlock-scan
    - vat
  variables:
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs"
    # reusing the VAT artifact dir to prevent redownloading
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/vat"
    ENV_FILENAME: "csv_output.env"
  script:
    - 'pip install --user --no-deps "${PIPELINE_REPO_DIR}"'
    - python3 "${PIPELINE_REPO_DIR}/stages/csv-output/pipeline_csv_gen.py"
    - python3 "${PIPELINE_REPO_DIR}"/stages/csv-output/excel_convert.py -i "${CSV_REPORT}"/ -o "${CSV_REPORT}"/"${CI_PROJECT_NAME}":"${IMAGE_VERSION}"-"${CI_PIPELINE_ID}"-justifications.xlsx
  artifacts:
    when: always
    paths:
      - "${CSV_REPORT}"
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
