lint:
  stage: validate-container-repository
  extends:
    - .setup_modules
  needs:
    - load-scripts
  id_tokens:
    VAT_TOKEN:
      aud: ${CI_SERVER_URL}
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/lint"
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: vat
  allow_failure:
    exit_codes: 100
  artifacts:
    paths:
      - "${ARTIFACT_DIR}"
    expire_in: 1 week
    when: always
    reports:
      dotenv: "${ARTIFACT_DIR}/variables.env"
  retry:
    max: 2
    when: runner_system_failure
  script:
    - 'mkdir -p "${ARTIFACT_DIR}"'
    - |
      if [[ "${CI_COMMIT_BRANCH}" == "master" || "${CI_COMMIT_BRANCH}" == "development" ]] && [[ "${CI_COMMIT_REF_PROTECTED}" != true ]]; then
        echo "This pipeline is running on an unprotected '${CI_COMMIT_BRANCH}' branch. Please protect '${CI_COMMIT_BRANCH}' before running the pipeline on this branch"
        echo "Exiting"
        exit 1
      fi
    - |
      if [[ "${CI_COMMIT_BRANCH}" == "master" ]] && "${STAGING_BASE_IMAGE}"; then
        echo "'STAGING_BASE_IMAGE' cannot be set on a 'master' branch."
        echo "Exiting"
        exit 1
      fi
    - set +e
    - 'python3 "${PIPELINE_REPO_DIR}/stages/validate-container-repository/lint/lint_jobs.py"'

trufflehog:
  stage: validate-container-repository
  image: registry1.dso.mil/ironbank/opensource/trufflehog/trufflehog3:3.0.6
  needs:
    - load-scripts
  variables:
    # This forces the trufflehog job to NOT perform a shallow clone
    GIT_DEPTH: 0
  script:
    - 'git config --global --add safe.directory "${CI_PROJECT_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/validate-container-repository/secret-scan/trufflehog.py"'
  retry:
    max: 2
    when: runner_system_failure
