setup:
  stage: setup
  allow_failure:
    exit_codes: 100
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - "${ARTIFACT_DIR}"
      - "${MODULES_CLONE_DIR}"
      - "${PIPELINE_REPO_DIR}"
    reports:
      dotenv:
        - "${ARTIFACT_DIR}/os.env"
        - "${ARTIFACT_DIR}/variables.env"
  id_tokens:
    VAT_TOKEN:
      aud: ${CI_SERVER_URL}
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/lint"
    GIT_DEPTH: 0
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: vat
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/0-setup/setup.sh"'