.preprocess:
  stage: .pre
  allow_failure: false
  except:
    refs:
      - tags
  dependencies: []

podman test:
  stage: .pre
  allow_failure: false
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/clamav-podman:temp
  script:
    - podman login --tls-verify=false -u ${ironbank_robot_user} -p "${ironbank_robot_pass} "registry1.dsop.io
    - podman pull --tls-verify=false ${REGISTRY_URL}/opensource/kubernetes-1.18/kubectl-1.18:latest
    - podman tag ${REGISTRY_URL}/opensource/kubernetes-1.18/kubectl:latest pipeline:img
    - vol = podman mount pipeline:img