import artifacts:
  stage: import artifacts
  image: "${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/all-in-one-fedora:1.0"
  dependencies:
    - load scripts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/import-artifacts"
  # Arguments.get().download is used to get download items
  # dccscrImport() calls ContributorResource, which performs validation of download.yaml file
  script:
    - '"${PIPELINE_REPO_DIR}/stages/import-artifacts/import-run.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: artifact.env
