import artifacts:
  stage: import artifacts
  tags:
    - ironbank
  dependencies:
    - load scripts
    - hardening_manifest
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/import-artifacts"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/import-artifacts/import-run.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: artifact.env
