#!/bin/bash
set -Eeuo pipefail
mkdir -p "${ARTIFACT_DIR}/external-resources/" "${ARTIFACT_DIR}/images/"
touch artifact.env

# Run the download script on the hardening_manifest.yaml file

if [ -f "${CI_PROJECT_DIR}/hardening_manifest.yaml" ]; then
  python3 "${PIPELINE_REPO_DIR}/stages/import-artifacts/downloader.py" -i "${CI_PROJECT_DIR}/hardening_manifest.yaml" -d "${ARTIFACT_DIR}"
elif [ -f "${ARTIFACT_DIR}/preflight/hardening_manifest.yaml" ]; then
  echo "Using autogenerated hardening_manifest.yaml"
  python3 "${PIPELINE_REPO_DIR}/stages/import-artifacts/downloader.py" -i "${ARTIFACT_DIR}/preflight/hardening_manifest.yaml" -d "${ARTIFACT_DIR}"
else
  echo "Internal Error: No hardening_mainfest.yaml file found"
  exit 1
fi
