.documentation:
  stage: documentation 
  only:
  - development
  - master
include:
  - local: /stages/documentation/sign_image.yaml
  - local: /stages/documentation/sign_manifest.yaml
  - local: /stages/documentation/write_json_documentation.yaml
