.documentation:
  stage: documentation
  only:
    - master
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/documentation"
    OPENSCAP_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/openscap/oscap-version.txt"
    TWISTLOCK_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/twistlock/twistlock-version.txt"
    ANCHORE_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/anchore/anchore-version.txt"
  dependencies:
    - load-scripts
    - hardening-manifest
    - base-image-validation
    - wl-compare-lint
    - build
    - anchore-scan
    - twistlock-scan
    - openscap-compliance
  before_script:
    - 'mkdir -p "${ARTIFACT_DIR}/reports"'
  artifacts:
    paths:
      - $ARTIFACT_DIR
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure

ib-manifest:
  extends: .documentation
  script:
    - '"${PIPELINE_REPO_DIR}/stages/documentation/ib-manifest-run.sh"'
  retry:
    max: 2
    when: runner_system_failure

write-json-docs:
  extends: .documentation
  script:
    - '"${PIPELINE_REPO_DIR}/stages/documentation/write-json-docs-run.sh"'
  retry:
    max: 2
    when: runner_system_failure
