.documentation:
  stage: documentation
  tags:
    - ironbank
  only:
    - development
    - master
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/documentation"
    SIG_FILE: signature
    OPENSCAP_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/openscap/oscap-version.txt"
    TWISTLOCK_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/twistlock/twistlock-version.txt"
    ANCHORE_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/anchore/anchore-version.txt"

documentation:
  extends: .documentation
  # include:
  #   - local: /stages/documentation/sign_image.yaml
  #   - local: /stages/documentation/sign_manifest.yaml
  #   - local: /stages/documentation/write_json_documentation.yaml
  script:
    - '"${PIPELINE_REPO_DIR}/stages/documentation/documentation.sh"'
  artifacts:
    paths:
      - $ARTIFACT_DIR
    expire_in: 1 week
