generate-allowlists:
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
      when: "on_success"
  stage: generate-allowlists
  dependencies:
    - load-scripts
    - anchore-scan
    - base-image-validation
    - wl-compare-lint
    - hardening-manifest
    - build
  variables:
    ALLOWLISTS: "${ARTIFACT_STORAGE}/allowlists"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/generate-allowlists/allowlister.py"'
  allow_failure: true
  artifacts:
    when: always
    paths:
      - "${ALLOWLISTS}"
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
