create-sbom:
  stage: post-build
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/sbom"
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/3-post-build/generate_sbom.py"'

create-tar:
  stage: post-build
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
  extends:
    - .setup_modules
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/tar"
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/3-post-build/create_tar.py"'
