.post-build:
  stage: post-build
  needs:
    - load-scripts
    - build
  retry:
    max: 2
    when: runner_system_failure

create-tar:
  extends:
    - .post-build
    - .setup_modules
  variables:
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/create_tar.py"'
  artifacts:
    when: always
    paths:
      - ${IMAGE_FILE}.tar
    expire_in: 1 week

create-sbom:
  extends: .post-build
  variables:
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom"
  artifacts:
    when: always
    paths:
      - "${SBOM_DIR}/"
    expire_in: 1 week
  image: "registry1.dso.mil/ironbank/anchore/enterprise/enterprise:4.4.1"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/generate_sbom.py"'

    
### Tidelift.com SaaS integration ######
### Job will create a 1:1 container image project alignment with the Tidelift Catalog
tidelift-upload:
  extends:
    - .post-build
  needs:
    - create-sbom
  variables:
    TIDELIFT_API_KEY: "${TIDELIFT_API_KEY}"
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom" 
    TIDELIFT_DIR: "${ARTIFACT_STORAGE}/tidelift"
    TIDELIFT_ORG_NAME: us-ironbank
    TIDELIFT_PROJECT_BRANCH: "${CI_COMMIT_BRANCH}"
    #set IB Tier Group to "General" as default for now. 
    IRONBANK_CLASSIFICATION: General  
    TIDELIFT_PROJECT_GROUP: "${IRONBANK_CLASSIFICATION}" 
    TIDELIFT_PROJECT_EXTERNAL_ID: "${IMAGE_NAME}-${IMAGE_TAG}-${CI_COMMIT_REF_NAME}"
    #SupplierName/SubGroup/projectname/tagnumber/branch/
    #parse the supplier name from "${IMAGE_NAME}" string 
    TIDELIFT_PROJECT_SUPPLIER:  "${IMAGE_NAME}" 
    TIDELIFT_PROJECT_SUPPLIERTYPE: "${IMAGE-TAG}"
    TIDELIFT_PROJECT_NAME: "${TIDELIFT_IMAGE_NAME}-${IMAGE_TAG}-${CI_COMMIT_BRANCH}"  
    #notes: "${TIDELIFT_IMAGE_NAME}" uses "${CI_PROJECT_NAME}"
    TIDELIFT_CATALOG_NAME: "${TIDELIFT_PROJECT_SUPPLIER}"
    #notes ref: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html 
    #Variables for Tidelift Reports
   # TIDELIFT_ALIGNMENT_ID:  TBD
   # TIDELIFT_CVE_REPORT_ID: TBD
    TIDELIFT_CVE_REPORT_NAME:  "${TIDELIFT_PROJECT_EXTERNAL_ID}_tidelift_cve_report.json"

  script:
    - cp ${SBOM_DIR}/sbom-cyclonedx-json.json cyclonedx.json
    - curl https://download.tidelift.com/cli/tidelift -o tidelift
    - echo "Setting permission"
    - chmod +x tidelift
    - echo "-******** PRINTING ENV VARIABLES ******"
    - cat /etc/os-release
    - grep '^VERSION' /etc/os-release
    - grep -E '^(VERSION|NAME)=' /etc/os-release
    - apk update
    - apk add yq
    - env | egrep $(yq '.variables | keys | ... comments = "" | map("^" + . + "=") | @csv' .gitlab-ci.yml | tr "," "|")