.post-build:
  stage: post-build
  needs:
    - load-scripts
    - build
  retry:
    max: 2
    when: runner_system_failure

create-tar:
  extends: .post-build
  variables:
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/post-build/create-tar.sh"'
  artifacts:
    when: always
    paths:
      - ${IMAGE_FILE}.tar
    expire_in: 1 week

create-sbom:
  extends: .post-build
  variables:
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom"
  artifacts:
    when: always
    paths:
      - "${SBOM_DIR}/"
    expire_in: 1 week
  image: "registry1.dso.mil/ironbank/anchore/engine/engine:1.0.0"
  script:
    - 'pip install --user "${PIPELINE_REPO_DIR}"'
    - python3 "${PIPELINE_REPO_DIR}/stages/post-build/generate_sbom.py"
