clamav image scan:
  stage: post-build
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/clamav-podman:temp
  dependencies:
    - build
  variables:
    ARTIFACT_DIR: ${ARTIFACT_FOLDER}/post-build/clamav-image-scan
  before_script:
    - mkdir -p "${ARTIFACT_DIR}"
  script:
    # - freshclam
    - podman pull --authfile=${DOCKER_AUTH_CONFIG} registry1.dsop.io/ironbank/opensource/kubernetes-1.18/kubectl-1.18:latest
    # - podman pull --tls-verify=false ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/docker-git-bash-python:3.7
    # - podman ps -a
    # - podman create ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/docker-git-bash-python:3.7
    # - podman ps -a
    # - clamscan -irv vol > output.txt
    # - cat output.txt
    # - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt | cut -d ' ' -f3)
    # - |
    #   if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
    #   then
    #     echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
    #     exit 1
    #   fi
  artifacts:
    when: always
    paths:
      - ${ARTIFACT_DIR}/
