.post-build:
  stage: post-build
  needs:
    - load-scripts
    - build
  retry:
    max: 2
    when: runner_system_failure

create-tar:
  extends:
    - .post-build
    - .setup_modules
  variables:
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/create_tar.py"'
  artifacts:
    when: always
    paths:
      - ${IMAGE_FILE}.tar
    expire_in: 1 week

create-sbom:
  extends: .post-build
  variables:
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom"
  artifacts:
    when: always
    paths:
      - "${SBOM_DIR}/"
    expire_in: 1 week
  image: "registry1.dso.mil/ironbank/anchore/enterprise/enterprise:4.4.1"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/generate_sbom.py"'

    
### Tidelift.com SaaS integration ######
### Job will create a 1:1 container image project alignment with the Tidelift Catalog
tidelift-upload:
  extends:
    - .post-build
  needs:
    - lint
    - build
    - create-sbom
  variables:
    TIDELIFT_API_KEY: "${TIDELIFT_API_KEY}"
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom" 
    TIDELIFT_DIR: "${ARTIFACT_STORAGE}/tidelift"
    TIDELIFT_ORG_NAME: us-ironbank
    TIDELIFT_PROJECT_BRANCH: "${CI_COMMIT_BRANCH}"
    #set IB Tier Group to "General" as default for now. 
    IRONBANK_CLASSIFICATION: General  
    TIDELIFT_PROJECT_GROUP: "${IRONBANK_CLASSIFICATION}" 
    IRONBANK_IMAGE_NAME: "${IMAGE_NAME}"
    IRONBANK_IMAGE_TAG: "${IMAGE_FULLTAG}"
    TIDELIFT_PROJECT_NAME: ""  
    TIDELIFT_PROJECT_EXTERNAL_ID: ""
    TIDELIFT_PROJECT_SUPPLIER:  "" 
    TIDELIFT_PROJECT_SUPPLIER_TYPE: ""
    TIDELIFT_PROJECT_TAG: ""
    #notes: "${TIDELIFT_IMAGE_NAME}" uses "${CI_PROJECT_NAME}"
    #notes ref: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html 
    #Variables for Tidelift Reports
   # TIDELIFT_ALIGNMENT_ID:  TBD
   # TIDELIFT_CVE_REPORT_ID: TBD
   # TIDELIFT_CVE_REPORT_NAME:  "${TIDELIFT_PROJECT_EXTERNAL_ID}_tidelift_cve_report.json"

  script:
    - cp ${SBOM_DIR}/sbom-cyclonedx-json.json cyclonedx.json
    - echo "Downloading Tidelift CLI binary file" 
    - curl https://download.tidelift.com/cli/tidelift -o tidelift
    - echo "Setting Tidelift CLI permissions and updating binary file"
    - chmod +x tidelift
    - ./tidelift selfupdate
  #  - jq --version
    - echo "-* PRINTING ENV VARIABLES *-"
  #  - env
    - echo "TIDELIFT_PROJECT_BRANCH= $TIDELIFT_PROJECT_BRANCH"
    - echo "TIDELIFT_PROJECT_GROUP= $TIDELIFT_PROJECT_GROUP"
    - |
      echo "-- Parsing IB IRONBANK_IMAGE_NAME and IRONBANK_IMAGE_TAG string values into Tidelift variable values --"
      a=($(echo "$IRONBANK_IMAGE_NAME" | tr '/' '\n'))
      b=($(echo "$IRONBANK_IMAGE_TAG" | tr ':' '\n'))
      TIDELIFT_PROJECT_SUPPLIER=${a[0]}
      TIDELIFT_PROJECT_SUPPLIER_TYPE=${a[1]}
      TIDELIFT_PROJECT_TAG=${b[1]}
      TIDELIFT_PROJECT_NAME="${a[2]} ${TIDELIFT_PROJECT_TAG} ${TIDELIFT_PROJECT_BRANCH}"
      TIDELIFT_PROJECT_EXTERNAL_ID="${TIDELIFT_PROJECT_SUPPLIER}/${TIDELIFT_PROJECT_SUPPLIER_TYPE}/${a[2]}/${TIDELIFT_PROJECT_TAG}"
          
      echo "IRONBANK_IMAGE_NAME=${IRONBANK_IMAGE_NAME}"
      echo "IRONBANK_IMAGE_TAG=${IRONBANK_IMAGE_TAG}"
      echo "Project Supplier: ${TIDELIFT_PROJECT_SUPPLIER}"
      echo "Project Supplier Org/Type: ${TIDELIFT_PROJECT_SUPPLIER_TYPE}"
      echo "Project Tag: ${TIDELIFT_PROJECT_TAG}"
      echo "Project Name: ${TIDELIFT_PROJECT_NAME}"
      echo "Project External ID: ${TIDELIFT_PROJECT_EXTERNAL_ID}"
    - echo "-- Done --"
    #Project Name: project-name+tagnumber+branch-name 
    #External Prj Identifier: SupplierName/SubGroup/projectname/tagnumber/
    - echo "-* Starting Tidelift Project Alignment w/Container Image SBOM -*"