clamav image scan:
  stage: post-build

  image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/clamav-podman:temp
  dependencies:
    - load scripts
    - build
  variables:
    CLAMAV_SCANS: ${ARTIFACT_STORAGE}/post-build/clamav-image-scan
  before_script:
    - mkdir -p "${CLAMAV_SCANS}"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/post-build/post_build.sh"'
  # - freshclam
  # - clamscan -irv vol > output.txt
  # - cat output.txt
  # - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt | cut -d ' ' -f3)
  # - |
  #   if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
  #   then
  #     echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
  #     exit 1
  #   fi
  artifacts:
    when: always
    paths:
      - ${CLAMAV_SCANS}/
    expire_in: 1 week
