.image-av-scan:
  stage: post-build
  allow_failure: true
  image: ${DOCKER_REGISTRY_URL}/dsop/ironbank-pipeline/clamav-podman:latest
  dependencies:
    - build
  variables:
    ARTIFACT_DIR: ${ARTIFACT_FOLDER}/post-build/clamav-image-scan
  before_script:
    - mkdir -p "${ARTIFACT_DIR}"
  script:
    - freshclam
    - docker run -v ${CI_PROJECT_DIR}/imagefs:/scan:ro tquinnelly/clamav-alpine:latest | tee ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt
    - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt | cut -d ' ' -f3)
    - |
      if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
      then
        echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
        exit 1
      fi
  after_script:
    - rm -rf ${CI_PROJECT_DIR}/imagefs
    - docker image rm -f tquinnelly/clamav-alpine:latest
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/pipeline-artifacts/
