clamav image scan:
  stage: post-build
  
  image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/clamav-podman:temp
  dependencies:
    - build
  variables:
    CLAMAV_SCANS: ${ARTIFACT_STORAGE}/post-build/clamav-image-scan
  before_script:
    - mkdir -p "${CLAMAV_SCANS}"
  script:
    - freshclam
    - clamscan -irv --max-filesize=4000M --max-scansize=4000M ${ARTIFACT_STORAGE}/build/ > ${CLAMAV_SCANS}/scan-image-clamav-report.txt
    - cat ${ARTIFACT_DIR}/scan-image-clamav-report.txt
    - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${ARTIFACT_DIR}/import-artifacts-clamav-report.txt | cut -d ' ' -f3)
    - |
        if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
        then
          echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
          exit 1
        fi
    # - freshclam
    # - clamscan -irv vol > output.txt
    # - cat output.txt
    # - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt | cut -d ' ' -f3)
    # - |
    #   if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
    #   then
    #     echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
    #     exit 1
    #   fi
  artifacts:
    when: always
    paths:
      - ${CLAMAV_SCANS}/
    expire_in: 1 week
