clamav image scan:
  stage: post-build
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/clamav-podman:temp
  dependencies:
    - build
  variables:
    ARTIFACT_DIR: ${ARTIFACT_FOLDER}/post-build/clamav-image-scan
  before_script:
    - mkdir -p "${ARTIFACT_DIR}"
  script:
    - freshclam
    - podman login --tls-verify=false -u ${ironbank_robot_user} -p registry1.dsop.io
    - podman pull ${REGISTRY_URL}/opensource/kubernetes-1.18/kubectl:latest
    - podman tag ${REGISTRY_URL}/opensource/kubernetes-1.18/kubectl:latest pipeline:img
    - vol = podman mount pipeline:img
    - clamscan -irv vol > output.txt
    - cat output.txt
    - INFECTED_CONTAINER_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-container.txt | cut -d ' ' -f3)
    - |
      if [ ${INFECTED_CONTAINER_FILES} -gt 0 ]
      then
        echo Malware detected in container! Number of findings: ${INFECTED_CONTAINER_FILES}
        exit 1
      fi

  artifacts:
    when: always
    paths:
      - ${ARTIFACT_DIR}/
