create-tar:
  stage: post-build

  needs:
    - load-scripts
    - build
  variables:
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/post-build/create-tar.sh"'
  artifacts:
    when: always
    paths:
      - ${IMAGE_FILE}.tar
    expire_in: 1 week
