.post-build:
  stage: post-build
  needs:
    - load-scripts
    - build
  retry:
    max: 2
    when: runner_system_failure

create-tar:
  extends:
    - .post-build
    - .setup_modules
  variables:
    IMAGE_FILE: "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/create_tar.py"'
  artifacts:
    when: always
    paths:
      - ${IMAGE_FILE}.tar
    expire_in: 1 week

create-sbom:
  extends: .post-build
  variables:
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom"
  artifacts:
    when: always
    paths:
      - "${SBOM_DIR}/"
    expire_in: 1 week
  image: "registry1.dso.mil/ironbank/anchore/enterprise/enterprise:4.4.1"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-build/generate_sbom.py"'

    
### Tidelift.com SaaS integration ######
### Job will create a 1:1 container image project alignment with the Tidelift Catalog
tidelift-upload:
  extends:
    - .post-build
  needs:
    - create-sbom
  variables:
    TIDELIFT_API_KEY: "${TIDELIFT_API_KEY}"
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom" 
    TIDELIFT_DIR: "${ARTIFACT_STORAGE}/tidelift"
    TIDELIFT_ORG_NAME: us-ironbank
    TIDELIFT_PROJECT_BRANCH: "${CI_COMMIT_BRANCH}"
    #set IB Tier Group to "General" as default for now. 
    IRONBANK_CLASSIFICATION: General  
    TIDELIFT_PROJECT_GROUP: "${IRONBANK_CLASSIFICATION}" 
    TIDELIFT_PROJECT_EXTERNAL_ID: "${IMAGE_NAME}-${IMAGE_TAG}-${CI_COMMIT_REF_NAME}"
    #SupplierName/SubGroup/projectname/tagnumber/branch/
    #parse the supplier name from "${IMAGE_NAME}" string 
    TIDELIFT_PROJECT_SUPPLIER:  "${IMAGE_NAME}" 
    TIDELIFT_PROJECT_SUPPLIERTYPE: "${IMAGE-TAG}"
    TIDELIFT_PROJECT_NAME: "${TIDELIFT_IMAGE_NAME}-${IMAGE_TAG}-${CI_COMMIT_BRANCH}"  
    #notes: "${TIDELIFT_IMAGE_NAME}" uses "${CI_PROJECT_NAME}"
    TIDELIFT_CATALOG_NAME: "${TIDELIFT_PROJECT_SUPPLIER}"
    #notes ref: https://docs.gitlab.com/ee/ci/variables/predefined_variables.html 
    #Variables for Tidelift Reports
   # TIDELIFT_ALIGNMENT_ID:  TBD
   # TIDELIFT_CVE_REPORT_ID: TBD
    TIDELIFT_CVE_REPORT_NAME:  "${TIDELIFT_PROJECT_EXTERNAL_ID}_tidelift_cve_report.json"

  script:
    - cp ${SBOM_DIR}/sbom-cyclonedx-json.json cyclonedx.json
    - curl https://download.tidelift.com/cli/tidelift -o tidelift
    - echo "Setting permission"
    - chmod +x tidelift
    - echo "-******** PRINTING ENV VARIABLES ******"
    - env
    - echo "-******** DEFINIG SCRIPT VARIABLE VALUES ******"
  #  - snap install yq --channel=v3/stable
  #  - env | egrep $(yq '.variables | keys | ... comments = "" | map("^" + . + "=") | @csv' .gitlab-ci.yml | tr "," "|")
    - echo `*****************************************************`
    - echo "TIDELIFT_PROJECT_BRANCH= $TIDELIFT_PROJECT_BRANCH"
    - echo "TIDELIFT_PROJECT_GROUP= $TIDELIFT_PROJECT_GROUP"
    - echo "TIDELIFT_PROJECT_EXTERNAL_ID= $TIDELIFT_PROJECT_EXTERNAL_ID"
    - echo "TIDELIFT_PROJECT_SUPPLIER= $TIDELIFT_PROJECT_SUPPLIER"
    - echo "TIDELIFT_PROJECT_SUPPLIERTYPE= $TIDELIFT_PROJECT_SUPPLIERTYPE"
    - echo "TIDELIFT_PROJECT_NAME= $TIDELIFT_PROJECT_NAME"
    - echo "TIDELIFT_CATALOG_NAME= $TIDELIFT_CATALOG_NAME"
    - echo "TIDELIFT_CVE_REPORT_NAME= $TIDELIFT_CVE_REPORT_NAME"

    - echo "-******** Predefined ENV VARIABLES ******"
    - echo "$CI_JOB_ID"
    - echo "$CI_COMMIT_REF_NAME"
    - echo "$CI_COMMIT_TAG"
    - echo "$CI_COMMIT_REF_SLUG"
    - echo "$CI_JOB_STAGE"
    - echo "$CI_JOB_NAME"
    - echo "$CI_REPOSITORY_URL"
    - echo "$CI_PIPELINE_TRIGGERED"
    - echo "$CI_JOB_MANUAL"
    - echo "$CI_JOB_TOKEN"
    - echo "$CI_RUNNER_ID"
    - echo "$CI_RUNNER_TAGS"
    - echo "$CI_RUNNER_VERSION"
    - echo "$CI_PIPELINE_ID"
    - echo "$CI_REGISTRY_USERNAME"
    - echo "$CI_REGISTRY_PASSWORD"
    - echo "$CI_PROJECT_DIR"
    - echo "$CI_PROJECT_ID"
    - echo "$CI_PROJECT_NAME"
    - echo "$CI_PROJECT_PATH"
    - echo "$CI_PROJECT_URL"
    - echo "$CI_REGISTRY"
    - echo "$CI_REGISTRY_IMAGE"
    - echo "$CI_SERVER"
    - echo "$CI_SERVER_NAME"
    - echo "$CI_SERVER_VERSION"
    - echo "$GITLAB_USER_ID"
    - echo "$GITLAB_USER_LOGIN"
    - echo "$GITLAB_USER_NAME"
    - echo "$GITLAB_FEATURES"
    - echo "$CI_PROJECT_TITLE"
    - echo "$CI_PAGES_DOMAIN"