.scan:
  stage: scan
  needs:
    - setup
    - build
    - scan-logic
  artifacts:
    when: always
    expire_in: 1 week

.scan-arm64:
  stage: scan
  needs:
    - setup
    - build-arm64
    - scan-logic-arm64
  artifacts:
    when: always
    expire_in: 1 week
  rules:
    - exists: 
      - Dockerfile_arm64

anchore-scan:
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
  extends: .scan
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/5-scan/anchore_scan.py"'
  artifacts:
    paths:
      - "${ANCHORE_SCANS}/"

anchore-scan-arm64:
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
  extends: .scan-arm64
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/5-scan/anchore_scan.py"'
  artifacts:
    paths:
      - "${ANCHORE_SCANS}/"

openscap-compliance:
  extends: .scan
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/oscap_scan.sh"'
  artifacts:
    paths:
      - "${OSCAP_SCANS}"
    reports:
      dotenv: oscap-compliance.env

openscap-compliance-arm64:
  extends: .scan-arm64
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/oscap_scan.sh"'
  artifacts:
    paths:
      - "${OSCAP_SCANS}"
    reports:
      dotenv: oscap-compliance.env

twistlock-scan:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  extends: .scan
  tags:
    - ironbank-dsop-privileged
  variables:
    VERSION_FILE: "${TWISTLOCK_SCANS}/twistlock-version.txt"
    CVE_FILE: "${TWISTLOCK_SCANS}/twistlock_cve.json"
    DETAIL_FILE: "${TWISTLOCK_SCANS}/twistcli-details.txt"
  script:
    - 'mkdir -p "${TWISTLOCK_SCANS}"'
    - 'podman pull --authfile "${DOCKER_AUTH_FILE_PULL}" "${IMAGE_TO_SCAN}"'
    - 'twistcli --version >"${VERSION_FILE}"'
    - 'twistcli images scan --address "${TWISTLOCK_URL}" --podman-path podman --custom-labels --output-file "${CVE_FILE}" --details "${IMAGE_TO_SCAN}" | tee "${DETAIL_FILE}"'
    - 'ls "${CVE_FILE}"'
    - 'chmod 0644 "${CVE_FILE}"'
  artifacts:
    paths:
      - "${TWISTLOCK_SCANS}/"

twistlock-scan-arm64:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  extends: .scan-arm64
  tags:
    - ironbank-dsop-privileged
  variables:
    VERSION_FILE: "${TWISTLOCK_SCANS}/twistlock-version.txt"
    CVE_FILE: "${TWISTLOCK_SCANS}/twistlock_cve.json"
    DETAIL_FILE: "${TWISTLOCK_SCANS}/twistcli-details.txt"
  script:
    - 'mkdir -p "${TWISTLOCK_SCANS}"'
    - 'podman pull --authfile "${DOCKER_AUTH_FILE_PULL}" "${IMAGE_TO_SCAN}"'
    - 'twistcli --version >"${VERSION_FILE}"'
    - 'twistcli images scan --address "${TWISTLOCK_URL}" --podman-path podman --custom-labels --output-file "${CVE_FILE}" --details "${IMAGE_TO_SCAN}" | tee "${DETAIL_FILE}"'
    - 'ls "${CVE_FILE}"'
    - 'chmod 0644 "${CVE_FILE}"'
  artifacts:
    paths:
      - "${TWISTLOCK_SCANS}/"