anchore-scan:
  stage: scan
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
    - scan-logic
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/anchore"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/5-scan/anchore_scan.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week

openscap-compliance:
  stage: scan
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
    - scan-logic
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/oscap_scan.sh"'
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/openscap"
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}"
    expire_in: 1 week

twistlock-scan-amd64:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  stage: scan
  needs:
    - setup
    - job: build-amd64
      optional: true
    - scan-logic
  tags:
    - ironbank-dsop-privileged
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/twistlock/amd64"
    PLATFORM: "amd64"
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/twistlock_scan.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  rules:
    - exists:
        - Dockerfile

twistlock-scan-arm64:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  stage: scan
  needs:
    - setup
    - job: build-arm64
      optional: true
    - scan-logic
  tags:
    - ironbank-dsop-privileged
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/twistlock/arm64"
    PLATFORM: "arm64"
    KUBERNETES_NODE_SELECTOR_IRONBANK: "ironbank=gitlab-runner-arm64"
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/twistlock_scan.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  rules:
    - if: $ENABLE_MULTIARCH != ""
      exists:
        - Dockerfile.arm64