.scan:
  stage: scan
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
    - scan-logic

anchore-scan:
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/anchore"
  extends: .scan
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/5-scan/anchore_scan.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week

openscap-compliance:
  extends: .scan
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/oscap_scan.sh"'
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/openscap"
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    reports:
      dotenv: "${ARTIFACT_DIR}/oscap-compliance.env"
    expire_in: 1 week

twistlock-scan:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  extends: .scan
  tags:
    - ironbank-dsop-privileged
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/twistlock"
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/5-scan/twistlock_scan.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
