rescan-or-rebuild:
  stage: rescan-or-rebuild
  # TODO: Remove when final testing of SBOMs is complete
  # rules:
  #   - when: never
  #     allow_failure: true
  dependencies:
    - load-scripts
    - build
    - create-sbom
  script:
    - 'pip install --user "${PIPELINE_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/rescan-or-rebuild/rescan_or_rebuild_jobs.py"'
  retry:
    max: 2
    when: runner_system_failure
