scan-logic:
  stage: scan-logic
  extends:
    - .setup_modules
  needs:
    - load-scripts
    - lint
    - build_x86
    - create-sbom-x86
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      dotenv: scan_logic.env
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/scan-logic/scan_logic_jobs.py"'
  retry:
    max: 2
    when: runner_system_failure
