scan-logic:
  stage: scan-logic
  # TODO: Remove when final testing of SBOMs is complete
  allow_failure: true
  dependencies:
    - load-scripts
    - lint
    - build
    - create-sbom
  script:
    - 'pip install --user "${PIPELINE_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/scan-logic/scan_logic_jobs.py"'
  artifacts:
    when: always
    expire_in: 1 week
    reports:
      dotenv: scan_logic.env
  retry:
    max: 2
    when: runner_system_failure
