.lint:
  stage: lint
  dependencies:
    - load-scripts
    - hardening-manifest
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/lint"
  before_script:
    - 'mkdir -p "${ARTIFACT_DIR}"'
  artifacts:
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    when: always
  retry:
    max: 2
    when: runner_system_failure

include:
  # - local: stages/lint/container-approval-status.yaml
  - local: stages/lint/base-image-validation.yaml
  - local: stages/lint/pipeline-auth-status.yaml
  - local: stages/lint/wl-compare-lint.yaml
  - local: stages/lint/trufflehog.yaml
  - local: stages/lint/folder-structure.yaml
  - local: stages/lint/hardening-manifest.yaml
  - local: stages/lint/registry-validation.yaml