check cves:
  stage: check cves
  tags:
    - ironbank
  dependencies:
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan

  script:
    - python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py"
