check-cves:
  stage: check-cves
  # allow_failure:
  #   exit_codes:
  #     - 100
  #     - 101
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure: true

    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure:
        exit_codes: 100
  dependencies:
    - hardening-manifest
    - load-scripts
    - base-image-validation
    - wl-compare-lint
    - twistlock-scan
    - openscap-compliance
    - anchore-scan
    - vat
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/check-cves/vat-response-parse.py"'
