check-cves:
  stage: check-cves
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure: true

    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure: false
  dependencies:
    - hardening-manifest
    - load-scripts
    - wl-compare-lint
    # - twistlock-scan
    # - openscap-compliance
    # - anchore-scan
  script:
    - |
      pip3 install jsonschema
      python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py"
      exit $?
