check cves:
  stage: check cves

  dependencies:
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan

  script:
    - '"${PIPELINE_REPO_DIR}/stages/check-cves/check-cves.sh"'
