check cves:
  stage: check cves
  rules:
    - if: '$CI_COMMIT_BRANCH == "check-cves-mm-int"'
      allow_failure: false
    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure: false
  tags:
    - ironbank
  dependencies:
    - hardening_manifest
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
  script:
    - python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py"

check cves failure notification:
  stage: check cves
  when: on_failure
  script: 
    - '"${PIPELINE_REPO_DIR}/stages/check-cves/mattermost-failure-webhook.sh"'