check cves:
  stage: check cves
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure:
        exit_codes:
          - 1
          - 3

    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure:
        exit_codes: 3

  tags:
    - ironbank
  dependencies:
    - hardening_manifest
    - load scripts
    - wl compare lint
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
  script:
    - |
      pip3 install jsonschema
      python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py"
      exit $?
