check cves:
  stage: check cves
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure: false
  tags:
    - ironbank
  dependencies:
    - hardening_manifest
    - load scripts
    - wl compare lint
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
  variables:
    # Put the vat findings from the vat api in the vat_findings directory
    VAT_FINDINGS: "${ARTIFACT_STORAGE}/vat_findings"
  script:
    - python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py"
  artifacts:
    when: always
    paths:
      - "${VAT_FINDINGS}"
    expire_in: 1 week

