check cves:
  stage: check cves
  rules:
    - if: '$CI_COMMIT_BRANCH != "master"'
      allow_failure: true
    - if: '$CI_COMMIT_BRANCH == "master"'
      allow_failure: false
  tags:
    - ironbank
  dependencies:
    - hardening_manifest
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan

  script:
    - |
      python3 "${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py" \
        --db "${vat_db_database_name}" \
        --user "${vat_db_connection_user}" \
        --host "${vat_db_host}" \
        --password "${vat_db_connection_pass}"
