check-cves:
  stage: check-cves
  allow_failure:
    exit_codes: 100
  dependencies:
    - load-scripts
    - lint
    - twistlock-scan
    - openscap-compliance
    - anchore-scan
    - vat
  script:
    - set +e
    - 'pip install "${PIPELINE_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/check-cves/vat-response-parse.py"'
  retry:
    max: 2
    when: runner_system_failure
