check-cves:
  stage: check-cves
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/jenkins-oscap-agent:1.1
  dependencies:
    - csv-output
  variables:
    ARTIFACT_DIR: ${ARTIFACT_STORAGE}/check-cves
  script:
    - python3 ${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py
  artifacts:
    when: always
    paths:
      - ${ARTIFACT_DIR}/