.check-cves:
  stage: check cves
  image: "${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/jenkins-oscap-agent:1.1"
  dependencies:
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
