check-cves:
  stage: check-cves
  allow_failure:
    exit_codes: 100
  dependencies:
    - load-scripts
    - lint
    - twistlock-scan
    - openscap-compliance
    - anchore-scan
    - vat
  script:
    - set +e
    - 'pip install --user "${PIPELINE_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/check-cves/vat-response-parse.py"'
  retry:
    max: 2
    when: runner_system_failure

check-findings:
  variables:
    TRIGGERING_PROJECT_ID: $CI_PROJECT_ID
    ROBOTNIK_COMMAND: projectfindings
    ROBOTNIK_SUBCOMMAND: check
  stage: check-cves
  allow_failure: true
  rules:
    - if: $SKIP_FINDINGS_TRIGGER
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - job: vat
      artifacts: false
  trigger:
    project: ironbank-tools/robotnik
    branch: main
