check-cves:
  stage: check-cves
  allow_failure:
    exit_codes: 100
  needs:
    - load-scripts
    - lint
    - twistlock-scan
    - openscap-compliance
    - anchore-scan
    - vat
  script:
    - 'python3 -m pip install --user --no-deps --no-build-isolation "${MODULES_IMPORT_PATH}"'
    - set +e
    - 'python3 "${PIPELINE_REPO_DIR}/stages/check-cves/vat_response_parse.py"'
  retry:
    max: 2
    when: runner_system_failure
