check cves:
  stage: check cves
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/jenkins-oscap-agent:1.1
  dependencies:
    - load scripts
    - twistlock scan
    - openscap cve
    - openscap compliance
    - anchore scan
  before_script:
    - repo_path="${CI_PROJECT_DIR}"
    - wl_image_path=$(echo ${CI_PROJECT_PATH} | sed -e 's/.*dsop\/\(.*\)/\1/')
  script:
    - python3 ${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py --image ${wl_image_path} --tag ${IMG_VERSION} --oscap ${ARTIFACT_STORAGE}/scan-results/openscap/report.html --oval ${ARTIFACT_STORAGE}/scan-results/openscap/report-cve.html --twistlock ${ARTIFACT_STORAGE}/scan-results/twistlock/${IMG_VERSION}.json --anchore-sec ${ARTIFACT_STORAGE}/scan-results/anchore/anchore_security.json --anchore-gates ${ARTIFACT_STORAGE}/scan-results/anchore/anchore_gates.json --glkey "${PYTHON_GL_KEY}" --branch "pipeline-test-project"
