check-cves:
  stage: check-cves
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/jenkins-oscap-agent:1.1
  dependencies:
    - csv-output
    - load scripts
  variables:
    CHECK_CVE_RESULTS: ${ARTIFACT_STORAGE}/check-cves
  before_script:
    - repo_path="${CI_PROJECT_DIR}"
    - wl_image_path=(${repo_path:13:200})
  script:
    - python3 ${PIPELINE_REPO_DIR}/stages/check-cves/pipeline_wl_compare.py --image $wl_image_path --tag $IMG_VERSION --oscap ${PIPELINE_REPO_DIR}/stages/csv-output/report.html --oval ${ARTIFACT_STORAGE}/scanning/openscap-cve/report-cve.html --twistlock ${PIPELINE_REPO_DIR}/stages/csv-output/${IMG_VERSION}.json --anchore-sec ${PIPELINE_REPO_DIR}/stages/csv-output/anchore_vulns_new.json --anchore-gates ${PIPELINE_REPO_DIR}/stages/csv-output/anchore_gates.json --branch $CI_COMMIT_BRANCH
  artifacts:                                                                                                                                                                     
    when: always
    paths:
      - ${CHECK_CVE_RESULTS}/


  # ./pipeline_wl_compare.py --image opensource/kubernetes-1.18/kubectl-1.18 --tag v1.18.8 
  # --oscap reports/openscap/report.html 
  # --oval reports/openscap/report-cve.html 
  # --twistlock reports/twistlock/v1.18.8.json 
  # --anchore-sec reports/anchore/anchore_vulns_new.json 
  # --anchore-gates reports/anchore/anchore_gates.json --branch master