upload-to-cds:
  stage: post-publish
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
    - scan-logic
    - vat
    - harbor
  when: manual
  extends:
    - .setup_modules
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $UPLOAD_TO_CDS == "True"
  variables:
    ARTIFACT_DIR: ${ARTIFACT_STORAGE}/cds
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: cds
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/8-post-publish/upload_to_cds.py"'

upload-to-s3:
  stage: post-publish
  extends:
    - .setup_modules
  resource_group: s3_phase
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  id_tokens:
    VAT_TOKEN:
      aud: ${CI_SERVER_URL}
  variables:
    #TODO: Put these in globals
    SCAN_DIRECTORY: "${ARTIFACT_STORAGE}/scan-results"
    DOCUMENTATION_DIRECTORY: "${ARTIFACT_STORAGE}/documentation"
    BUILD_DIRECTORY: "${ARTIFACT_STORAGE}/build"
    SBOM_DIRECTORY: "${ARTIFACT_STORAGE}/sbom"
    VAT_DIRECTORY: "${ARTIFACT_STORAGE}/vat"
    BASE_BUCKET_DIRECTORY: container-scan-reports
    DOCUMENTATION_FILENAME: documentation
    ARTIFACT_DIR: ${ARTIFACT_STORAGE}/documentation
    REPORT_TAR_NAME: ${CI_PROJECT_NAME}-${IMAGE_VERSION}-reports-signature.tar.gz
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: ibfe
  needs:
    - setup
    - job: build-amd64
      optional: true
    - job: build-arm64
      optional: true
    - create-sbom
    - scan-logic
    - anchore-scan
    - job: twistlock-scan-amd64
      optional: true
    - job: twistlock-scan-arm64
      optional: true
    - openscap-compliance
    - generate-documentation
    - vat
  script:
    - 'python "${PIPELINE_REPO_DIR}/pipeline1/8-post-publish/upload_artifacts.py"'
  artifacts:
    paths:
      - reports/
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure

manifest:
  stage: post-publish
  needs:
    - setup
    - create-sbom
    - job: harbor
    optional: true
  script:
    - '"${PIPELINE_REPO_DIR}/pipeline1/8-post-publish/manifest.sh"'
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: sign
  rules:
    - if: '$ENABLE_MULTIARCH && $ENABLE_MULTIARCH != ""'
      exists:
        - Dockerfile.arm64
