version: "3"
services:
  ironbank-pipeline:
    build:
      context: ..
      dockerfile: ./.devcontainer/Dockerfile
    entrypoint: /bin/sh -c "while sleep 1000; do :; done"
    hostname: ironbank-pipeline
    user: python
    volumes:
      - ..:/workspace:cached
