generate-documentation:
  stage: generate-documentation
  extends:
    - .setup_modules
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/documentation"
    OPENSCAP_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/openscap/oscap-version.txt"
    TWISTLOCK_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/twistlock/twistlock-version.txt"
    ANCHORE_VERSION_FILE: "${ARTIFACT_STORAGE}/scan-results/anchore/anchore-version.txt"
    # Put generated csv report in the scan-results folder
    CSV_REPORT: "${ARTIFACT_STORAGE}/scan-results/csvs"
    # reusing the VAT artifact dir to prevent redownloading
    VAT_ARTIFACT_DIR: "${ARTIFACT_STORAGE}/vat"
    ENV_FILENAME: "csv_output.env"

  needs:
    - load-scripts
    - lint
    - build-x86
    - scan-logic-x86
    - anchore-scan
    - twistlock-scan
    - openscap-compliance
    - vat
  script:
    - 'mkdir -p "${ARTIFACT_DIR}/reports"'
    - '"${PIPELINE_REPO_DIR}/stages/generate-documentation/ib-manifest-run.sh"'
    - '"${PIPELINE_REPO_DIR}/stages/generate-documentation/write-json-docs-run.sh"'
    - python3 "${PIPELINE_REPO_DIR}/stages/generate-documentation/pipeline_csv_gen.py"
    - python3 "${PIPELINE_REPO_DIR}"/stages/generate-documentation/excel_convert.py -i "${CSV_REPORT}"/ -o "${CSV_REPORT}"/"${CI_PROJECT_NAME}":"${IMAGE_VERSION}"-"${CI_PIPELINE_ID}"-justifications.xlsx
  artifacts:
    when: always
    paths:
      - $ARTIFACT_DIR
      - "${CSV_REPORT}"
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
