openscap scans:
  extends: .scanning
  stage: scanning
  before_script:
    - DOCKER_IMAGE_PATH=$(podman load -i "${ARTIFACT_STORAGE}"/build/"${CI_PROJECT_NAME}"-"${CI_PIPELINE_ID}".tar | awk '{print $3}')
    - export ${DOCKER_IMAGE_PATH}
    - BASE_IMAGE_TYPE=$(podman inspect -f '{{index .Labels "com.redhat.component"}}' "${DOCKER_IMAGE_PATH}")
    - |
      if [[ "${BASE_IMAGE_TYPE}" == "" ]]; then
        BASE_IMAGE_TYPE=$(podman inspect -f '{{index .Labels "os_type"}}' "${DOCKER_IMAGE_PATH}")
        if [[ "${BASE_IMAGE_TYPE}" == "" ]]; then
          BASE_IMAGE_TYPE=$(podman inspect -f '{{index .Labels "mil.dso.ironbank.os-type"}}' "${DOCKER_IMAGE_PATH}")
          if [[ "${BASE_IMAGE_TYPE}" == "" ]]; then
            labels=$(podman inspect -f '{{index .Labels}}' "${DOCKER_IMAGE_PATH}")
            echo "Unknown image type. Can't choose security guide. labels: ${labels}"
            exit 1
          fi
        fi
      fi
    - export ${BASE_IMAGE_TYPE}
  include:
    - local: stages/scanning/openscap/openscap-compliance.yaml
    - local: stages/scanning/openscap/openscap-cve.yaml
