vat:
  stage: vat
  image: ${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/python:pyyaml
  allow_failure: true
  variables:
    ARTIFACT_DIR: ${ARTIFACT_STORAGE}/scan-results/csvs/
    OPENSCAP: ${ARTIFACT_STORAGE}/scan-results/openscap
  only:
    - development
  before_script:
    - export BASE_BUCKET_DIRECTORY="container-scan-reports"    
    - export REMOTE_REPORT_DIRECTORY="$(date +%FT%T)_${CI_COMMIT_SHA}"
    - export S3_HTML_LINK=${S3_REPORT_BUCKET}/${BASE_BUCKET_DIRECTORY}/${CI_PROJECT_NAME}/${IMG_VERSION}/${REMOTE_REPORT_DIRECTORY}
  script:
    - pip3 install --upgrade pip setuptools wheel pandas mysql mysql-connector-python minepy
    - | 
        if [ "${CI_COMMIT_BRANCH}" == "development"]; then 
          python3 ${PIPELINE_REPO_DIR}/stages/vat/vat_import.py --db 'vat-db' --user ${vat_db_connection_user} --host mariadb.ironbank-vat-test.svc.cluster.local --csv_dir ${ARTIFACT_DIR} --jenkins '${BUILD_NUMBER}' --container '${CI_PROJECT_NAME}' --version '${IMG_VERSION}' --parent '${PARENT_NAME}' --password '${vat_db_connection_pass}' --parent_version '${PARENT_TAG}' --scan_date '$(date +%FT%T)' --link '${OPENSCAP}/' --debug
        fi
  artifacts:
    when: always
    paths:
      - ${ARTIFACT_DIR}/
    expire_in: 1 week
