vat:
  # checks if project is a pipeline-test-project and if so, prevents job from running
  # else, checks if the branch is development and if so, runs the job if all prior jobs succeed
  rules:
    - if: $CI_PROJECT_PATH =~ /pipeline-test-project/
      when: never
    - when: "on_success"
  id_tokens:
    VAT_TOKEN:
      aud: ${CI_SERVER_URL}
  stage: vat
  # Load in the IMAGE_VERSION variable from load-scripts env
  needs:
    - load-scripts
    - lint
    - build
    - scan-logic
    - anchore-scan
    - openscap-compliance
    - twistlock-scan
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/vat"
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: vat
  script:
    - 'mkdir -p "${ARTIFACT_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/vat/vat_import.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
