vat:
  # checks if project is a pipeline-test-project and if so, prevents job from running
  # else, checks if the branch is development and if so, runs the job if all prior jobs succeed
  rules:
    - if: $CI_PROJECT_PATH =~ /pipeline-test-project/
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: "on_success"
  stage: vat
  # Load in the IMAGE_VERSION variable from load-scripts env
  dependencies:
    - load-scripts
    - build
    - wl-compare-lint
    - hardening-manifest
    - anchore-scan
    - openscap-compliance
    - twistlock-scan
  variables:
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: vat
    ANCHORE_ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/anchore/"
    TWISTLOCK_ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/openscap/"
    OPENSCAP_ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/twistlock/"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/vat/vat-run-api.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_STORAGE}/vat_request.json"
    expire_in: 1 week