vat:
  stage: vat
  extends:
    - .setup_modules
  id_tokens:
    VAT_TOKEN:
      aud: ${CI_SERVER_URL}

  # Load in the IMAGE_VERSION variable from load-scripts env
  needs:
    - load-scripts
    - lint
    - build
    - scan-logic
    - anchore-scan
    - openscap-compliance
    - twistlock-scan
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/vat"
    KUBERNETES_SERVICE_ACCOUNT_OVERWRITE: vat
  script:
    - 'mkdir -p "${ARTIFACT_DIR}"'
    - '"${PIPELINE_REPO_DIR}/stages/vat/vat-run-api.sh"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  retry:
    max: 2
    when: runner_system_failure
