vat:
  # checks if project is a pipeline-test-project and if so, prevents job from running
  # else, checks if the branch is development and if so, runs the job if all prior jobs succeed
  rules:
    - if: $CI_PROJECT_PATH =~ /pipeline-test-project/
      when: never
    - if: '$CI_COMMIT_BRANCH == "development"'
      when: "on_success"
  stage: vat
  image: "${GITLAB_INTERNAL_REGISTRY}/ironbank-tools/ironbank-pipeline/python:pyyaml"
  tags:
    - ironbank
  # Load in the IMG_VERSION variable from load scripts env
  dependencies:
    - load scripts
    - csv output
    - wl compare lint
    - hardening_manifest
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/csvs/"
    OPENSCAP: "${ARTIFACT_STORAGE}/scan-results/openscap"
  script:
    - '"${PIPELINE_REPO_DIR}/stages/vat/vat-run.sh"'
