vat:
  stage: vat
  # Load in the IMG_VERSION variable from load scripts env
  dependencies:
    - load scripts
    - csv output
    - wl compare lint
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/scan-results/csvs/"
    OPENSCAP: "${ARTIFACT_STORAGE}/scan-results/openscap"
  only:
    - development
  script:
    - '"${PIPELINE_REPO_DIR}/stages/vat/vat-run.sh"'
