check-findings:
  stage: post-vat
  allow_failure: true
  rules:
    - if: $SKIP_FINDINGS_TRIGGER
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - job: vat
      artifacts: false
  variables:
    TRIGGERING_PROJECT_ID: $CI_PROJECT_ID
    ROBOTNIK_COMMAND: projectfindings
    ROBOTNIK_SUBCOMMAND: check
  trigger:
    project: ironbank-tools/robotnik
    branch: main

update-vat-badges:
  stage: post-vat
  allow_failure: true
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - vat
  variables:
    BADGE_DIRECTORY: ./badges
  before_script:
    - python3 -m pip install --user anybadge
    - 'mdkir "${BADGE_DIRECTORY}"'
  script:
    - python3 vat_status.py
  artifacts:
    paths:
      - '"${BADGE_DIRECTORY}"'
