include:
  - local: stages/post-vat/check-cves/base.yaml
#
check-findings:
  variables:
    PROJECT: $CI_PROJECT_ID
    MODULES: project_findings
  stage: post-vat
  allow_failure: true
  rules:
    - if: $SKIP_FINDINGS_TRIGGER
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - job: vat
      artifacts: false
  trigger:
    project: ironbank-tools/containers/cht-automation/bots/ib-11
    branch: master
