include:
- local: stages/post-vat/check-cves/base.yaml


check-findings:
  variables:
    TRIGGERING_PROJECT_ID: $CI_PROJECT_ID
    ROBOTNIK_COMMAND: projectfindings
    ROBOTNIK_SUBCOMMAND: check
  stage: post-vat
  allow_failure: true
  rules:
    - if: $SKIP_FINDINGS_TRIGGER
      when: never
    - if: $CI_COMMIT_BRANCH == "master"
  needs:
    - job: vat
      artifacts: false
  trigger:
    project: cht-automation/bots/robotnik
    branch: main
