check-cves:
  stage: post-vat
  extends:
    - .setup_modules
  allow_failure:
    exit_codes: 100
  needs:
    - load-scripts
    - lint
    - twistlock-scan
    - openscap-compliance
    - anchore-scan
    - vat
  script:
    - set +e
    - 'python3 "${PIPELINE_REPO_DIR}/stages/post-vat/check-cves/vat_response_parse.py"'
