.publish:
  stage: publish
  allow_failure: true
include:  
  - local: /stages/publish/sign_image.yaml
  - local: /stages/publish/sign_manifest.yaml
  - local: /stages/publish/write_json_documentation.yaml
