publish:
  stage: publish
  allow_failure: true
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/all-in-one-fedora:1.0
  variables:
    IMAGE_FILE: ${CI_PROJECT_NAME}-${IMG_VERSION}
    IMAGE_SIG_FILE: ${CI_PROJECT_NAME}-${IMG_VERSION}
  dependencies:
    - build
  before_script:
    - podman load -i ${ARTIFACT_STORAGE}/build/${IMAGE_FILE}.tar
      #    - tar -xvf ${ARTIFACT_STORAGE}/build/${IMAGE_FILE}.tar manifest.json
    - echo ${IB_CONTAINER_GPG_KEY} | base64 -d > key
    - mkdir -p tmp_gpg
  script:
    - skopeo copy --log-level=debug --dest-authfile ${DOCKER_AUTH_CONFIG_TEST} ${STAGING_REGISTRY_URL}/${IM_NAME}:${IMG_VERSION} docker://${REGISTRY_URL_TEST}/${IM_NAME}:${IMG_VERSION}
    - gpg --homedir ./tmp_gpg --import --batch --passphrase ${IB_CONTAINER_SIG_KEY_PASSPHRASE} key
    - echo "pinentry-mode loopback" >> ./tmp_gpg/gpg.conf
    - gpg --detach-sign --homedir ./tmp_gpg -o ${IMAGE_SIG_FILE}.sig --armor --yes --batch --passphrase ${IB_CONTAINER_SIG_KEY_PASSPHRASE} ${IMAGE_FILE}.tar
    - ls && ls tmp_gpg
    - GPG_VERSION=$(gpg --version | grep '(?<=gpg .GnuPG.)([^0-9]+)([0-9]+[.][0-9]+[.][0-9]+)' -oP)
    - IMAGE_SHA=$(sha256sum ${IMAGE_NAME}.tar | grep -E '^[a-zA-Z0-9]+' -o)
     
