.sbom-access-log:
  stage: sbom-access-log
  needs:
    - load-scripts
    - build
    - post-build
  retry:
    max: 2
    when: runner_system_failure


parse-access-log:
  extends: .sbom-access-log
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/scripts/modules/access_log_parser.py" --allow-errors "${ARTIFACT_DIR}/access_log"'
