.sbom-access-log:
  stage: sbom-access-log
  dependencies:
    - load-scripts
    - build
    - create-sbom
  retry:
    max: 2
    when: runner_system_failure

parse-sbom-access-log:
  extends: .sbom-access-log
  variables:
    SBOM_DIR: "${ARTIFACT_STORAGE}/sbom"
    ACCESS_LOG_DIR: "${ARTIFACT_STORAGE}/build"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/sbom-access-log/sbom_access_log_parser.py" --allow-errors "${SBOM_DIR}/sbom-json.json" "${ACCESS_LOG_DIR}/access_log"'
