.base:
  before_script:
    # need to keep same path for poetry to use same virtual env
    - source $(poetry env info -C ${MODULES_DEPS_PATH} --path)/bin/activate
    - ls ${MODULES_PACKAGE_PATH}
    - pip install --no-deps --no-build-isolation ${MODULES_PACKAGE_PATH}
    # need to source the virtual env because `poetry shell` requires an interactive shell

variables:
  # modules in image (used to get venv for the deps)
  MODULES_PROJECT: "ironbank-modules"
  # updated modules cloned down in load scripts (used for the package)
  MODULES_CLONE_DIR: "${ARTIFACT_STORAGE}/${MODULES_PROJECT}"
  MODULES_SUBDIR: "ironbank"
  MODULES_DEPS_PATH: "${MODULES_PROJECT}/${MODULES_SUBDIR}"
  MODULES_PACKAGE_PATH: "${MODULES_CLONE_DIR}/${MODULES_SUBDIR}"
