.base:
  before_script:
    - poetry install -C ${MODULES_IMPORT_PATH} --only-root
    # need to source the virtual env because `poetry shell` requires an interactive shell
    - source $(poetry env info -C ${MODULES_IMPORT_PATH} --path)/bin/activate

variables:
  MODULES_REPO_DIR: "${ARTIFACT_STORAGE}/ironbank-modules"
  MODULES_IMPORT_PATH: "${MODULES_REPO_DIR}/ironbank"
