include:
    - local: templates/globals.yaml
    
    - local: stages/preflight/base.yaml
    
    - local: stages/lint/base.yaml
    
    - local: stages/import-artifacts/base.yaml

    - local: stages/scan-artifacts/clamav-scan.yaml
    
    - local: stages/build/base.yaml
    
    - local: stages/post-build/base.yaml
    
    # Scanning files
    # - local: stages/scanning/base.yaml
    - local: stages/scanning/openscap-compliance.yaml
    - local: stages/scanning/openscap-cve.yaml
    - local: stages/scanning/twistlock.yaml
    - local: stages/scanning/anchore.yaml
    
    - local: stages/csv-output/base.yaml
    
    - local: stages/check-cves/base.yaml
    
    - local: stages/publish/base.yaml
    
    - local: stages/vat/base.yaml
