image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.10.9
stages:
  - preprocess
  - lint
  - secret-scan
  - import-artifacts
  - build
  - post-build
  - scan-logic
  - scanning
  - vat
  - post-vat
  - csv-output
  - check-cves
  - documentation
  - harbor
  - s3-publish

include:
  - local: templates/base.yaml
  - local: stages/preprocess/load-scripts.yaml
  - local: stages/lint/lint.yaml
  - local: stages/secret-scan/trufflehog.yaml
  - local: stages/import-artifacts/import-artifacts.yaml
  - local: stages/build/base.yaml
  - local: stages/post-build/base.yaml
  - local: stages/scan-logic/base.yaml
  - local: stages/scanning/base.yaml
  - local: stages/vat/base.yaml
  - local: stages/post-vat/base.yaml
  - local: stages/csv-output/base.yaml
  - local: stages/check-cves/base.yaml
  - local: stages/documentation/base.yaml
  - local: stages/harbor/harbor.yaml
  - local: stages/s3/upload-to-s3.yaml

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

variables:
  # Gitlab CI vars
  # several CI vars are passed from the trigger job in trigger.yaml
  # Scan reports
  SCAN_RESULTS: "${ARTIFACT_STORAGE}/scan-results"
  ANCHORE_SCANS: "${SCAN_RESULTS}/anchore"
  TWISTLOCK_SCANS: "${SCAN_RESULTS}/twistlock"
  OSCAP_SCANS: "${SCAN_RESULTS}/openscap"
  OSCAP_CVE_XML_FILENAME: "report-cve.xml"
  OSCAP_CVE_HTML_FILENAME: "report-cve.html"
