#services:
#  - name: docker:19.03-dind-rootless
#    command: ["--experimental"]

stages:
  
  ### preprocess stage
  # clone down the templates directory for use in later stages
  # Requirements:
  # - executor image with git
  - preprocess
  
  ### preflight stage
  # check folder structure, check build variables
  # Requirements:
  # - None
  - preflight
  
  ### lint stage
  # yaml lint (ci file, download.yaml), dockerfile lint, wl compare lint
  # Requirements:
  # - executor image with Python 3.x installed
  - lint

  ### pre-build stage
  # download artifacts/clamav scan, image signature?
  # Requirements:
  # - executor image with Python 3.x installed
  # - executor image with docker (or podman) installed
  - pre-build
  
  ### build stage
  # build image w version tag and create tar file
  # Requirements:
  # - executor image with docker installed
  # NOTE: Executor image must have docker installed in order to work properly with Notary for image signing
  - build

  ### post-build stage
  # clamav scan of the image
  - post-build
  
  ### scanning stage
  # twistlock, oscap, and anchore scans
  - scanning
  
  ### create csv output
  - csv-output
  
  ### check cve stage
  - check-cves
  
  ### publish stage
  # publish artifacts to S3 (runs on master), push to harbor
  - publish
    
  ### VAT stage (runs on dev)
  - vat

include:
  - local: stages/preprocess/load-scripts.yaml
#   - local: stages/preprocess/base.yaml

variables:
  ARTIFACT_FOLDER: "ci_artifacts"
  PIPELINE_REPO_DIR: "${ARTIFACT_FOLDER}/ironbank_pipeline"
  PYTHON_GITLAB_KEY: "${PYTHON_GITLAB_KEY}"
  IMAGE_NAME: "${CI_PROJECT_PATH}"
  GIT_SSL_NO_VERIFY: "1"
