image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.9.1

stages:
  - preprocess
  - lint
  - secret-scan
  - os-type
  - pipeline-trigger

include:
  - local: stages/preprocess/load-scripts.yaml
  - local: stages/lint/lint.yaml
  - local: stages/secret-scan/trufflehog.yaml


image-inspect:
  stage: os-type
  needs:
    - load-scripts
    - lint
  script:
    - 'pip install --user "${PIPELINE_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/pipeline-trigger/trigger.py"'
  artifacts:
    when: always
    reports:
      dotenv: template.env

trigger:
  stage: pipeline-trigger
  needs:
    - image-inspect
  variables:
    TARGET_BRANCH: $TARGET_BRANCH
  trigger:
    include:
      - project: ironbank-tools/ironbank-pipeline
        file: 'templates/${TEMPLATE}'
        ref: $TARGET_BRANCH
    strategy: depend

variables:
  # Gitlab CI vars
  ARTIFACT_STORAGE: "ci-artifacts"
  PIPELINE_REPO_DIR: "${ARTIFACT_STORAGE}/ironbank_pipeline"
  GIT_SSL_NO_VERIFY: "1"
  TARGET_BRANCH: master
  # Controls if ironbank-staging is the source registry for base images
  STAGING_BASE_IMAGE: ""
