image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.10.9

stages:
  - preprocess
  - lint
  - secret-scan
  - os-type
  - pipeline-trigger
  - release

# only run if non-master branch or protected tag
workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: never

include:
  - local: templates/cut-tag.yaml
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
  - local: templates/shared_vars.yaml
  - local: templates/setup_modules.yaml
  - local: templates/trigger-jobs.yaml
