image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.9.1

stages:
  - init
  - test
  - pipeline

os-type:
  stage: init
  script:
    - echo "Init job"
    - echo "TEMPLATE=ubi" >template.env
  artifacts:
    when: always
    reports:
      dotenv: template.env

test:
  stage: test
  needs: os-type
  script:
    - echo $TEMPLATE

trigger:
  stage: pipeline
  needs:
    - os-type
  trigger:
    include:
      - project: templates/${TEMPLATE}.yaml@ironbank-tools/ironbank-pipeline
        file: templates/${TEMPLATE}.yaml
        ref: master

