image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.10.12

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - preprocess
  # - lint
  - secret-scan
  # - os-type
  - validate-container-metadata
  - pipeline-trigger

include:
  - local: templates/shared_vars.yaml
  - local: templates/setup_modules.yaml
  - local: stages/preprocess/load-scripts.yaml
  # - local: stages/lint/validate-hardening-manifest.yaml
  - local: stages/secret-scan/trufflehog.yaml

# image-inspect:
#   stage: os-type
#   extends:
#     - .setup_modules
#   needs:
#     - load-scripts
#     - job: validate-hardening-manifest
#       artifacts: false
#     - job: trufflehog
#       artifacts: false
#   script:
#     - 'python3 "${PIPELINE_REPO_DIR}/stages/os-type/image_inspect.py"'
#   artifacts:
#     when: always
#     reports:
#       dotenv: template.env
#   retry:
#     max: 2
#     when: always


validate-container-metadata:
  stage: validate-container-metadata
  extends:
    - .setup_modules
  needs:
    - load-scripts
    - job: trufflehog
      artifacts: false
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/lint/validate_hardening_manifest.py"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/os-type/image_inspect.py"'
  artifacts:
    when: always
    reports:
      dotenv: template.env
  retry:
    max: 2
    when: always

trigger:
  stage: pipeline-trigger
  needs:
    - validate-container-metadata
  # dotenv vars can be passed but can't be used to configure the job
  # https://docs.gitlab.com/ee/ci/pipelines/downstream_pipelines.html#pass-dotenv-variables-created-in-a-job
  variables:
    TEMPLATE: $TEMPLATE
    BASE_IMAGE_TYPE: $BASE_IMAGE_TYPE
  trigger:
    include:
      - project: ironbank-tools/ironbank-pipeline
        file: "templates/downstream/${TEMPLATE}"
        ref: $TARGET_BRANCH
    strategy: depend
