image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner@sha256:321811246b1a481ed316c98f943f2c635bf15783d32b9a206e04cfea8b6f184f

workflow:
  rules:
    - if: $CI_COMMIT_BRANCH

stages:
  - preprocess
  - lint
  - secret-scan
  - os-type
  - pipeline-trigger

include:
  - local: templates/base.yaml
  - local: stages/preprocess/load-scripts.yaml
  - local: stages/lint/validate-hardening-manifest.yaml
  - local: stages/secret-scan/trufflehog.yaml

image-inspect:
  stage: os-type
  needs:
    - load-scripts
    - job: validate-hardening-manifest
      artifacts: false
    - job: trufflehog
      artifacts: false
  script:
    - 'python3 -m pip install --user --no-deps --no-build-isolation "${MODULES_REPO_DIR}"'
    - 'python3 "${PIPELINE_REPO_DIR}/stages/os-type/image_inspect.py"'
  artifacts:
    when: always
    reports:
      dotenv: template.env

trigger:
  stage: pipeline-trigger
  needs:
    - image-inspect
  variables:
    BASE_IMAGE_TYPE: $BASE_IMAGE_TYPE
    LOGLEVEL: $LOGLEVEL
    STAGING_PIPELINE: $STAGING_PIPELINE
    TARGET_BRANCH: $TARGET_BRANCH
    TEMPLATE: $TEMPLATE
    GIT_SSL_NO_VERIFY: $GIT_SSL_NO_VERIFY
    STAGING_BASE_IMAGE: $STAGING_BASE_IMAGE
    ARTIFACT_STORAGE: $ARTIFACT_STORAGE
    PIPELINE_REPO_DIR: $PIPELINE_REPO_DIR
    MODULES_DEPS_DIR: $MODULES_REPO_DIR
    MODULES_PACKAGE_PATH: $MODULES_IMPORT_PATH

  trigger:
    include:
      - project: ironbank-tools/ironbank-pipeline
        file: "templates/${TEMPLATE}"
        ref: $TARGET_BRANCH
    strategy: depend

variables:
  # Gitlab CI vars
  ARTIFACT_STORAGE: "ci-artifacts"
  PIPELINE_REPO_DIR: "${ARTIFACT_STORAGE}/ironbank_pipeline"
  GIT_SSL_NO_VERIFY: "1"
  TARGET_BRANCH: master
  # Controls if ironbank-staging is the source registry for base images
  STAGING_BASE_IMAGE: ""
