image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.10.9

stages:
  - preprocess
  - lint
  - secret-scan
  - os-type
  - pipeline-trigger
  - release

workflow:
  - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
    when: never

include:
  - local: templates/cut-tag.yaml
    rules:
      - if: $CI_COMMIT_BRANCH == "master"
  - local: templates/shared_vars.yaml
  - local: templates/setup_modules.yaml
  - local: stages/preprocess/load-scripts.yaml
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
  - local: stages/lint/validate-hardening-manifest.yaml
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
  - local: stages/secret-scan/trufflehog.yaml
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
  - local: templates/trigger-jobs.yaml
    rules:
      - if: $CI_COMMIT_BRANCH && $CI_COMMIT_BRANCH != "master"
      - if: $CI_COMMIT_TAG && $CI_COMMIT_REF_PROTECTED == "true"
