image: registry1.dso.mil/ironbank/ironbank-pipelines/pipeline-runner:v0.9.1

stages:
  - init
  - pipeline

os-type:
  stage: init
  script:
    - echo "Init job"
    - echo "TEMPLATE=alpine" >template.env
  artifacts:
    when: always
    reports:
      dotenv: template.env

trigger:
  stage: pipeline
  needs:
    - os-type
  variables:
    TEMPLATE: $TEMPLATE
    TARGET_BRANCH: $TARGET_BRANCH
  trigger:
    include:
      - project: ironbank-tools/ironbank-pipeline
        file: 'templates/${TEMPLATE}.yaml'
        ref: test-trigger
    strategy: depend
