.pre-build:
  stage: pre-build
  # image: image-registry.openshift-image-registry.svc:5000/jenkins/jenkins-oscap-agent:1.1
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/docker-git-bash-python:3.7
  allow_failure: true

import_artifacts:
  extends: .pre-build
  # Arguments.get().download is used to get download items
  # dccscrImport() calls ContributorResource, which performs validation of download.yaml file
  image: ${GITLAB_INTERNAL_REGISTRY}/dsop/ironbank-pipeline/docker-git-bash-python:3.7
  servVices:
    - name: docker:dind
      alias: docker
      entrypoint: ["cat"]
  script:
    - sleep 10000
  artifacts:
    when: always
    paths:
      - ${ARTIFACT_FOLDER}/pipeline-artifacts/application-artifacts
  variables:
    DOCKER_HOST: tcp://localhost:2375 
    DOCKER_TLS_CERTDIR: ""

# image_signature:
#   extends: .import_artifacts
#   allow_failure: true
#   image: image-registry.openshift-image-registry.svc:5000/jenkins/jenkins-oscap-agent:1.1
#   services:
#     - name: docker:dind
#   before_script:
#     - docker version
#   script:
#     - IMAGE=$(grep "FROM" Dockerfile | cut -d " " -f2)
#     - docker trust inspect ${IMAGE} | tee ${CI_PROJECT_DIR}/pipeline-artifacts/report-image-trust.txt
#   artifacts:
#     when: always
#     paths:
#       - ${CI_PROJECT_DIR}/pipeline-artifacts/

