.pre-build:
  stage: pre-build
  image: image-registry.openshift-image-registry.svc:5000/jenkins/jenkins-oscap-agent:1.1
  allow_failure: true

.import_artifacts:
  extends: .pre-build
  # Arguments.get().download is used to get download items
  # dccscrImport() calls ContributorResource, which performs validation of download.yaml file
  image: image-registry.openshift-image-registry.svc:5000/jenkins/jenkins-oscap-agent:1.1
  before_script:
    - mkdir ${CI_PROJECT_DIR}/pipeline-artifacts/application-artifacts
    # - sudo pip3 install pyyaml --upgrade
    - echo ${GITLAB_INTERNAL_REGISTRY}
    - podman pull ${GITLAB_INTERNAL_REGISTRY}/clamav:0.102.4
  script:
    - python3 "${PIPELINE_REPO_DIR}/stages/pre-build/downloader.py" -i ${CI_PROJECT_DIR}/download.yaml -d ${CI_PROJECT_DIR}/pipeline-artifacts/application-artifacts
    - podman run -v ${CI_PROJECT_DIR}/pipeline-artifacts/application-artifacts:/scan:ro ${GITLAB_INTERNAL_REGISTRY}/clamav:0.102.4 | tee ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-artifacts.txt
    - INFECTED_ARTIFACT_FILES=$(grep -e "^Infected files:" ${CI_PROJECT_DIR}/pipeline-artifacts/report-clamav-artifacts.txt | cut -d ' ' -f3)
    - |
      if [ ${INFECTED_ARTIFACT_FILES} -gt 0 ]
      then
        echo Malware detected in vendor/customer artifacts! Number of findings: ${INFECTED_ARTIFACT_FILES}
        exit 1
      fi
  after_script:
    - docker image rm -f tquinnelly/clamav-alpine:latest
  artifacts:
    when: always
    paths:
      - ${CI_PROJECT_DIR}/pipeline-artifacts/

# image_signature:
#   extends: .import_artifacts
#   allow_failure: true
#   image: ${GITLAB_INTERNAL_REGISTRY}/platform/docker-git-bash:stable
#   services:
#     - name: docker:dind
#   before_script:
#     - docker version
#   script:
#     - IMAGE=$(grep "FROM" Dockerfile | cut -d " " -f2)
#     - docker trust inspect ${IMAGE} | tee ${CI_PROJECT_DIR}/pipeline-artifacts/report-image-trust.txt
#   artifacts:
#     when: always
#     paths:
#       - ${CI_PROJECT_DIR}/pipeline-artifacts/

