# Set this for your top level group in gitlab
# all projects will exist in this group at https://<staging_url>/dsop/<tester>
tester: Kenn

branch: 771-temp-branch
src_gitlab_url: repo1.dso.mil
dest_gitlab_url: code-ib-zelda.staging.dso.mil
group: dsop
clone_dir: staging_projects
ci_file: .gitlab-ci.yml
templates: templates
default_project_branch: master
# project path in gitlab
projects:
  - gl_path: redhat/ubi/ubi8
    dest_project_name: ubi8
  - gl_path: google/distroless/static
    dest_project_name: static
  - gl_path: redhat/openjdk/openjdk11
    dest_project_name: openjdk11
  - gl_path: aiml/airflow/airflow
    dest_project_name: airflow
  - gl_path: suse/bci/bci-base
    dest_project_name: bci-base
    # branch: master   # --- branch can be set at a per project level
