scanning:
  stage: scanning
  allow_failure: true
  script: 
  - echo "beginning scans"
  #  dependencies:
  #    - post-build
include:
  - local: stages/scanning/openscap-compliance.yaml
  - local: stages/scanning/openscap-cve.yaml
  - local: stages/scanning/twistlock.yaml
  - local: stages/scanning/anchore.yaml
