.scanning:
  stage: scanning
  needs:
    - load-scripts
    - build-x86
    - scan-logic-x86
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    when: always
    expire_in: 1 week

anchore-scan:
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
  extends: .scanning
  image: "registry1.dso.mil/ironbank/anchore/enterprise/enterprise:4.4.1"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/scanning/anchore/anchore_scan.py"'
  artifacts:
    paths:
      - "${ANCHORE_SCANS}/"
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
      - unknown_failure

openscap-compliance:
  extends: .scanning
  image: registry1.dso.mil/ironbank/ironbank-pipelines/ib-oscap-redhat:1.0.0
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/stages/scanning/openscap/oscap_scan.sh"'
  artifacts:
    paths:
      - "${OSCAP_SCANS}"
    reports:
      dotenv: oscap-compliance.env
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
      - unknown_failure

twistlock-scan:
  image: registry1.dso.mil/ironbank-apps/ironbank-pipelines/pipeline-runner:v0.10.14
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  extends: .scanning
  tags:
    - ironbank-dsop-privileged
  variables:
    VERSION_FILE: "${TWISTLOCK_SCANS}/twistlock-version.txt"
    CVE_FILE: "${TWISTLOCK_SCANS}/twistlock_cve.json"
    DETAIL_FILE: "${TWISTLOCK_SCANS}/twistcli-details.txt"
  script:
    - 'mkdir -p "${TWISTLOCK_SCANS}"'
    - 'podman pull --authfile "${DOCKER_AUTH_FILE_PULL}" "${IMAGE_TO_SCAN}"'
    - 'twistcli --version >"${VERSION_FILE}"'
    - 'twistcli images scan --address "${TWISTLOCK_URL}" --podman-path podman --custom-labels --output-file "${CVE_FILE}" --details "${IMAGE_TO_SCAN}" | tee "${DETAIL_FILE}"'
    - 'ls "${CVE_FILE}"'
    - 'chmod 0644 "${CVE_FILE}"'
  artifacts:
    paths:
      - "${TWISTLOCK_SCANS}/"
  retry:
    max: 2
    when:
      - runner_system_failure
      - api_failure
      - stuck_or_timeout_failure
      - unknown_failure
