#scanning:
.scanning:
  stage: scanning
  tags:
    - ironbank
  #  dependencies:
  #    - post-build
include:
  - local: stages/scanning/openscap/base.yaml
  - local: stages/scanning/twistlock.yaml
  - local: stages/scanning/anchore/base.yaml
