.scanning:
  stage: scanning
  needs:
    - load-scripts
    - build
    - scan-logic
  retry:
    max: 2
    when: runner_system_failure
  artifacts:
    when: always
    expire_in: 1 week

anchore-scan:
  id_tokens:
    ANCHORE_PASSWORD:
      aud: ${CI_SERVER_URL}
  variables:
    PYTHON_LOG_LEVEL: "INFO"
  extends: .scanning
  image: "registry1.dso.mil/ironbank/anchore/enterprise/enterprise:4.4.1"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/stages/scanning/anchore/anchore_scan.py"'
  artifacts:
    paths:
      - "${ANCHORE_SCANS}/"

openscap-compliance:
  extends: .scanning
  image: registry1.dso.mil/ironbank/ironbank-pipelines/oscap-podman:v0.1.1
  tags:
    - ironbank-dsop-privileged
  script:
    - '"${PIPELINE_REPO_DIR}/stages/scanning/openscap/oscap-compliance-run.sh"'
  artifacts:
    paths:
      - "${OSCAP_SCANS}"
    reports:
      dotenv: oscap-compliance.env

twistlock-scan:
  id_tokens:
    TWISTLOCK_PASSWORD:
      aud: ${CI_SERVER_URL}
  extends: .scanning
  image: registry1.dso.mil/ironbank-apps/rootless-twistcli:22.12.415
  variables:
    VERSION_FILE: "${TWISTLOCK_SCANS}/twistlock-version.txt"
    CVE_FILE: "${TWISTLOCK_SCANS}/twistlock_cve.json"
    DETAIL_FILE: "${TWISTLOCK_SCANS}/twistcli-details.txt"
  script:
    - 'mkdir -p "${TWISTLOCK_SCANS}"'
    - 'podman pull --authfile "${DOCKER_AUTH_FILE_PULL}" "${IMAGE_TO_SCAN}"'
    - 'twistcli --version >"${VERSION_FILE}"'
    - 'twistcli images scan --address "${TWISTLOCK_URL}" --podman-path podman --custom-labels --output-file "${CVE_FILE}" --details "${IMAGE_TO_SCAN}" | tee "${DETAIL_FILE}"'
    - 'ls "${CVE_FILE}"'
    - 'chmod 0644 "${CVE_FILE}"'
  artifacts:
    paths:
      - "${TWISTLOCK_SCANS}/"


rapidfort-scan:
  extends: .scanning
  tags:
    - ironbank-dsop-privileged
  image: registry1.dso.mil/ironbank/rapidfort/runner:1.1.24-rfhardened
  variables:
    RF_ROOT_URL: $RF_ROOT_URL
    RF_ACCESS_ID: $RF_ACCESS_ID
    RF_SECRET_ACCESS_KEY: $RF_SECRET_ACCESS_KEY
  script:
    - 'podman pull --authfile "${DOCKER_AUTH_FILE_PULL}" "${IMAGE_TO_SCAN}"'
    - 'rfstub "${IMAGE_TO_SCAN}" --verbose'
    - podman run --rm -d --name "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}" --volume=/tests/:/tmp --cap-add=SYS_PTRACE "${IMAGE_TO_SCAN}-rfstub"
    - podman exec "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}" bash -c "/tmp/dc_coverage.sh"
    - podman exec "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}" bash -c "/tmp/redis_coverage.sh"
    - podman stop "${CI_PROJECT_NAME}-${CI_PIPELINE_ID}"
    - rfharden "${IMAGE_TO_SCAN}-rfstub" && echo "Hardened Done" || echo "Hardened Failed"
    - podman images