.scanning:
  stage: scanning
  allow_failure: true
  #  dependencies:
  #    - post-build
  before_script:
  - mkdir -p ${ARTIFACT_DIR}
include:
  - local: stages/scanning/openscap-compliance.yaml
  - local: stages/scanning/openscap-cve.yaml
  - local: stages/scanning/twistlock.yaml
  - local: stages/scanning/anchore.yaml
