# IMPORTANT: The name of this stage/job is must not be changed from "build" without first reconfiguring runners in the bootstrap
build:
  stage: build
  extends:
    - .setup_modules
  tags:
    - ironbank-dsop-build
  needs:
    - setup
    - import-artifacts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/build.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: build.env

build-arm64:
  # This is the only job that NEEDS to run on an arm64 node. Its easy to just specify it until I create an arm64 pipeline image.
  image: ${IAM_ACCOUNT_ID}.dkr.ecr.us-gov-west-1.amazonaws.com/ironbank/ironbank-pipelines/pipeline-runner:v0.10.13-arm64
  stage: build
  extends:
    - .setup_modules
  tags:
    - ironbank-dsop-build
  needs:
    - setup
    - import-artifacts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build"
    KUBERNETES_NODE_SELECTOR_IRONBANK: "ironbank=gitlab-runner-arm64"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/build.py" "--arm64-build"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
    reports:
      dotenv: build.env
  rules:
    - if: $BUILD_ARM64 == "True"