# IMPORTANT: The name of this stage/job is must not be changed from "build" without first reconfiguring runners in the bootstrap
build:
  stage: build
  extends:
    - .setup_modules
  tags:
    - ironbank-dsop-build
  needs:
    - setup
    - import-artifacts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/build.py"'
    - 'source build.env'
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/generate_sbom.py"'
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/scan_logic_jobs.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
      - "${SBOM_DIR}/"
    expire_in: 1 week
    reports:
      dotenv:
        - build.env
        - scan_logic.env
