build-amd64:
  stage: build
  extends:
    - .setup_modules
  tags:
    - ironbank-dsop-build
  needs:
    - setup
    - import-artifacts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build/amd64"
    PLATFORM: "amd64"
  script:
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/build.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  rules:
    - exists:
        - Dockerfile

build-arm64:
  stage: build
  extends:
    - .setup_modules
  tags:
    - ironbank-dsop-build
  needs:
    - setup
    - import-artifacts
  variables:
    ARTIFACT_DIR: "${ARTIFACT_STORAGE}/build/arm64"
    KUBERNETES_NODE_SELECTOR_IRONBANK: "ironbank=gitlab-runner-arm64"
    PLATFORM: "arm64"
  script:
    # Also by copying the Dockerfile.arm64 over the Dockerfile the correct arguments are passed when the image is being built.
    - "cp -f Dockerfile.arm64 Dockerfile"
    - 'python3 "${PIPELINE_REPO_DIR}/pipeline1/2-build/build.py"'
  artifacts:
    when: always
    paths:
      - "${ARTIFACT_DIR}/"
    expire_in: 1 week
  rules:
    # - exists:
    #     - Dockerfile.arm64
    # $MULTI_ARCH_BUILD_ALLOWED is a project variable to prevent unauthorized arm64 builds.
    - if: $MULTI_ARCH_BUILD_ALLOWED == "True" && exists("Dockerfile.arm64")
